on:
  push:
    branches:
      - master

name: Deploy

permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "8.7.6"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        env:
          DEPLOY_PRIME_URL: https://api.docs.stylehound.xyz
          DEPLOY_BASE_URL: /
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STYLEHOUND_465508 }}
          projectId: stylehound-465508
          channelId: live
