on:
  push:
    branches:
      - master

name: Deploy to GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "8.7.6"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        env:
          DEPLOY_PRIME_URL: https://api.docs.stylehound.xyz
          DEPLOY_BASE_URL: /
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: build
          destination: "api.docs.stylehound.xyz"
          parent: false
